version: "3.0"
services:
  server:
    build: ./web
    ports: ['5000:5000']
    volumes: ['./web:/app']
    depends_on:
      requirements:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    links:
      - db
  
  requirements:
    image: python:3.11
    volumes: ['./web:/app']
    working_dir: /app
    command: pip install -r requirements.txt

  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5123:5432
    env_file:
      - ./web/.env
    volumes:
      - ./pData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s